### ISSUE TITLE
Attack vector: 

### ISSUE THREAD

**Issue by schulzrinne** [flack/quickform#17]
Malicious users can trigger an error condition (Warning) by using array inputs in GET or POST, e.g., argument "name[0]" instead of "name". This affects all the rules and rendering. For example,

vendor/openpsa/quickform/lib/HTML/QuickForm/input.php:81 | HTML_Common->_getAttrString

Example:
index.php?logon=Log+on&username=vgxerkio&_qf__login=1&name[0]=foo

**Comment by flack** [comment]
So, I'm a bt conflicted about this: It doesn't really seem like a big deal, because the "attacker" can only produce a warning on their own browser (and only if a production server is configured to show warnings, which is not exactly best practice). 

Ideally, quickform should of course do sanity checks before setting values from POST/GET data, but integrating those at this point seems really really risky in terms of backwards compatibility. So I'm thinking of maybe simply doing something like this (in `HTML_Common`):

```php 
    function _getAttrString($attributes)
    {
        $strAttr = '';

        if (is_array($attributes)) {
            $charset = self::charset();
            foreach ($attributes as $key => $value) {
                if (is_scalar($value)) {   // <== this check is new
                    $strAttr .= ' ' . $key . '="' . htmlspecialchars($value, ENT_COMPAT, $charset) . '"';
                }
            }
        }
        return $strAttr;
    }
```

This would get rid of the warning without too much risk (it would break use cases where someone passes in an object with a `__toString` method, but idk if that's even possible, let alone a good idea). Of course, the spoofed input would still be in quickform's internal data structures, so the underlying problem would still be there.

Thoughts, opinions?

**Comment by schulzrinne** [comment]
In my case, the Warning triggers an email alert, as I suspect is common for
web sites of any complexity, as I need to know when there's a potential
problem (and security issues often also yield notices, errors and warnings
as the attacker tries out attack vectors). Thus, these attacks generate a
fair amount of garbage email.

I agree with your solution. Unfortunately, a similar problem exists in all
the checking functions, too, e.g.,

openpsa/quickform/lib/HTML/QuickForm/Rule/Range.php

It isn't obvious to me why a non-scalar value can reach the validation
function.

**Comment by flack** [comment]
Well, the problem is that the GET/POST data gets imported into quickform wholesale:

https://github.com/flack/quickform/blob/master/lib/HTML/QuickForm.php#L265

When you call `addElement` or similar, this line is triggered:

https://github.com/flack/quickform/blob/master/lib/HTML/QuickForm.php#L494

which calls

https://github.com/flack/quickform/blob/master/lib/HTML/QuickForm/element.php#L265

and that in turn calls

https://github.com/flack/quickform/blob/master/lib/HTML/QuickForm/element.php#L233

So if the array key matches, the value gets imported. An potential solution would be to do 

```php
        if (isset($values[$elementName]) && is_scalar($values[$elementName])) {
            return $values[$elementName];
        }
```

This would prevent all array values from entering the system (and I think it would fix the validation issue, too). The only problem is that this function gets called from all over the place, so it's pretty hard to tell if such a change would break some legitimate use cases, especially since we don't have any unit tests. If you have forms of reasonable complexity (with groups, file uploads, etc) and you feel adventurous, you could try to run the above patch locally and see if it causes any issues. If it doesn't, we could do this change, otherwise, we'd have to try and add `is_scalar` checks to validation and whereever else warnings pop up

**Comment by schulzrinne** [comment]
I will try our your suggestion. My system has probably close to hundred
forms, exercising almost all aspects of QuickForm.

**Comment by flack** [comment]
@schulzrinne any news on the testing? If you still need time, I would do an interim release with only the `HTML_Common` change (because that one makes sense regardless) and some other stuff I've been asked for

**Comment by schulzrinne** [comment]
I wouldn't call it a systematic, but so far, no problem.

**Comment by flack** [comment]
@schulzrinne I tested this now on some of my forms and got errors almost immediately. I think if you use groups, array values are actually legitimate (because they get assigned recursively). I have thus added `is_scalar` checks to the validators where appropriate and to `HTML_Common`. If you still see warnings, let me know, otherwise, I'd close this as fixed

**Comment by flack** [comment]
No more feedback ==> closing as fixed.
