### ISSUE TITLE
count() compatibility with PHP >= 7.2

### ISSUE THREAD

**Issue by arcticlinux** [flack/quickform#22]
I'm not sure entirely what form was submitted on our side that caused this error, but count() has been one of the only breaking changes we found in going to PHP 7.2.  We generally wrapped with is_array() because is_countable isn't available until 7.3

`PHP message: PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /var/www/treetime.ca/vendor/openpsa/quickform/lib/HTML/QuickForm.php on line 268" while reading response header from upstream`

https://github.com/flack/quickform/blob/61d2ecd1f871da777720d626cc0fdcde544da74b/lib/HTML/QuickForm.php#L268

**Comment by flack** [comment]
hm, that is strange, because `submitValues` and `submitFiles` come from `$_POST`, `$_GET` and `$_FILES` respectively. At least inside of this function, they are never any other type than `array`, so it seems like something else might be broken in your scenario. So we could add an `is_array` gate (although `is_countable` would probably be more accurate), or we could simply use `!empty()` here, but I think that would only mask the earlier error. So if possible, I would like to pinpoint what exactly is not an array and why first

**Comment by arcticlinux** [comment]
I'll try and track it down

**Comment by arcticlinux** [comment]
It looks like the code was reinitializing a form after it has been submitted, so we can show a blank form to the user on the same page by re-using the same form object and just blanking it out via:

unset($_POST);
$this->rawPost = [];
$this->formObj = null;
$this->initializeForm();

I'm just going to set $_POST=[]; instead of the unset.
